//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.4927
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 이 소스 코드는 xsd, 버전=2.0.50727.3038에서 자동 생성되었습니다.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("VisualStudioProject", Namespace="", IsNullable=false)]
public partial class VisualStudioProjectType {
    
    private VisualStudioProjectTypePlatform[] platformsField;
    
    private object[] toolFilesField;
    
    private VisualStudioProjectTypePublishingData publishingDataField;
    
    private ConfigurationType[] configurationsField;
    
    private object[] referencesField;
    
    private object[] filesField;
    
    private VisualStudioProjectTypeGlobal[] globalsField;
    
    private string projectTypeField;
    
    private VisualStudioProjectTypeVersion versionField;
    
    private string projectGUIDField;
    
    private string rootNamespaceField;
    
    private string keywordField;
    
    private string nameField;
    
    private string assemblyReferenceSearchPathsField;
    
    private string manifestKeyFileField;
    
    private string manifestCertificateThumbprintField;
    
    private string manifestTimestampURLField;
    
    private bool signManifestsField;
    
    private bool signManifestsFieldSpecified;
    
    private bool signAssemblyField;
    
    private bool signAssemblyFieldSpecified;
    
    private string assemblyOriginatorKeyFileField;
    
    private bool delaySignField;
    
    private bool delaySignFieldSpecified;
    
    private bool generateManifestsField;
    
    private bool generateManifestsFieldSpecified;
    
    private string targetZoneField;
    
    private string excludedPermissionsField;
    
    private string targetFrameworkVersionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public VisualStudioProjectType() {
        this.projectTypeField = "Visual C++";
        this.versionField = VisualStudioProjectTypeVersion.Item700;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Platform", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisualStudioProjectTypePlatform[] Platforms {
        get {
            return this.platformsField;
        }
        set {
            this.platformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DefaultToolFile", typeof(VisualStudioProjectTypeDefaultToolFile), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ToolFile", typeof(VisualStudioProjectTypeToolFile), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public object[] ToolFiles {
        get {
            return this.toolFilesField;
        }
        set {
            this.toolFilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualStudioProjectTypePublishingData PublishingData {
        get {
            return this.publishingDataField;
        }
        set {
            this.publishingDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Configuration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ConfigurationType[] Configurations {
        get {
            return this.configurationsField;
        }
        set {
            this.configurationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ActiveXReference", typeof(VisualStudioProjectTypeActiveXReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("AssemblyReference", typeof(VisualStudioProjectTypeAssemblyReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProjectReference", typeof(VisualStudioProjectTypeProjectReference), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public object[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("File", typeof(FileType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Filter", typeof(FilterType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public object[] Files {
        get {
            return this.filesField;
        }
        set {
            this.filesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Global", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisualStudioProjectTypeGlobal[] Globals {
        get {
            return this.globalsField;
        }
        set {
            this.globalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProjectType {
        get {
            return this.projectTypeField;
        }
        set {
            this.projectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(VisualStudioProjectTypeVersion.Item700)]
    public VisualStudioProjectTypeVersion Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProjectGUID {
        get {
            return this.projectGUIDField;
        }
        set {
            this.projectGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RootNamespace {
        get {
            return this.rootNamespaceField;
        }
        set {
            this.rootNamespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Keyword {
        get {
            return this.keywordField;
        }
        set {
            this.keywordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AssemblyReferenceSearchPaths {
        get {
            return this.assemblyReferenceSearchPathsField;
        }
        set {
            this.assemblyReferenceSearchPathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ManifestKeyFile {
        get {
            return this.manifestKeyFileField;
        }
        set {
            this.manifestKeyFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ManifestCertificateThumbprint {
        get {
            return this.manifestCertificateThumbprintField;
        }
        set {
            this.manifestCertificateThumbprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ManifestTimestampURL {
        get {
            return this.manifestTimestampURLField;
        }
        set {
            this.manifestTimestampURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SignManifests {
        get {
            return this.signManifestsField;
        }
        set {
            this.signManifestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SignManifestsSpecified {
        get {
            return this.signManifestsFieldSpecified;
        }
        set {
            this.signManifestsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SignAssembly {
        get {
            return this.signAssemblyField;
        }
        set {
            this.signAssemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SignAssemblySpecified {
        get {
            return this.signAssemblyFieldSpecified;
        }
        set {
            this.signAssemblyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AssemblyOriginatorKeyFile {
        get {
            return this.assemblyOriginatorKeyFileField;
        }
        set {
            this.assemblyOriginatorKeyFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool DelaySign {
        get {
            return this.delaySignField;
        }
        set {
            this.delaySignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DelaySignSpecified {
        get {
            return this.delaySignFieldSpecified;
        }
        set {
            this.delaySignFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool GenerateManifests {
        get {
            return this.generateManifestsField;
        }
        set {
            this.generateManifestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenerateManifestsSpecified {
        get {
            return this.generateManifestsFieldSpecified;
        }
        set {
            this.generateManifestsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetZone {
        get {
            return this.targetZoneField;
        }
        set {
            this.targetZoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ExcludedPermissions {
        get {
            return this.excludedPermissionsField;
        }
        set {
            this.excludedPermissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetFrameworkVersion {
        get {
            return this.targetFrameworkVersionField;
        }
        set {
            this.targetFrameworkVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypePlatform {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FileType {
    
    private object[] itemsField;
    
    private string relativePathField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File", typeof(FileType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("FileConfiguration", typeof(ConfigurationType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RelativePath {
        get {
            return this.relativePathField;
        }
        set {
            this.relativePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConfigurationType {
    
    private ConfigurationTypeTool[] toolField;
    
    private ConfigurationTypeDeploymentTool[] deploymentToolField;
    
    private ConfigurationTypeDebuggerTool[] debuggerToolField;
    
    private string nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationTypeTool[] Tool {
        get {
            return this.toolField;
        }
        set {
            this.toolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeploymentTool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationTypeDeploymentTool[] DeploymentTool {
        get {
            return this.deploymentToolField;
        }
        set {
            this.deploymentToolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DebuggerTool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationTypeDebuggerTool[] DebuggerTool {
        get {
            return this.debuggerToolField;
        }
        set {
            this.debuggerToolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConfigurationTypeTool {
    
    private string nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConfigurationTypeDeploymentTool {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConfigurationTypeDebuggerTool {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FilterType {
    
    private object[] itemsField;
    
    private string nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File", typeof(FileType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Filter", typeof(FilterType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeDefaultToolFile {
    
    private string fileNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeToolFile {
    
    private string relativePathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RelativePath {
        get {
            return this.relativePathField;
        }
        set {
            this.relativePathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypePublishingData {
    
    private VisualStudioProjectTypePublishingDataPublishingItem[] itemsField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PublishingItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualStudioProjectTypePublishingDataPublishingItem[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypePublishingDataPublishingItem {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeActiveXReference {
    
    private ConfigurationType[] referenceConfigurationField;
    
    private string controlGUIDField;
    
    private float controlVersionField;
    
    private string localeIDField;
    
    private string wrapperToolField;
    
    private string copyLocalField;
    
    private bool copyLocalDependenciesField;
    
    private bool copyLocalSatelliteAssembliesField;
    
    private bool useInBuildField;
    
    private bool useDependenciesInBuildField;
    
    public VisualStudioProjectTypeActiveXReference() {
        this.copyLocalDependenciesField = true;
        this.copyLocalSatelliteAssembliesField = true;
        this.useInBuildField = true;
        this.useDependenciesInBuildField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferenceConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationType[] ReferenceConfiguration {
        get {
            return this.referenceConfigurationField;
        }
        set {
            this.referenceConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ControlGUID {
        get {
            return this.controlGUIDField;
        }
        set {
            this.controlGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float ControlVersion {
        get {
            return this.controlVersionField;
        }
        set {
            this.controlVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocaleID {
        get {
            return this.localeIDField;
        }
        set {
            this.localeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WrapperTool {
        get {
            return this.wrapperToolField;
        }
        set {
            this.wrapperToolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CopyLocal {
        get {
            return this.copyLocalField;
        }
        set {
            this.copyLocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalDependencies {
        get {
            return this.copyLocalDependenciesField;
        }
        set {
            this.copyLocalDependenciesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalSatelliteAssemblies {
        get {
            return this.copyLocalSatelliteAssembliesField;
        }
        set {
            this.copyLocalSatelliteAssembliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseInBuild {
        get {
            return this.useInBuildField;
        }
        set {
            this.useInBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseDependenciesInBuild {
        get {
            return this.useDependenciesInBuildField;
        }
        set {
            this.useDependenciesInBuildField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeAssemblyReference {
    
    private ConfigurationType[] referenceConfigurationField;
    
    private string relativePathField;
    
    private string assemblyNameField;
    
    private string copyLocalField;
    
    private bool copyLocalDependenciesField;
    
    private bool copyLocalSatelliteAssembliesField;
    
    private bool useInBuildField;
    
    private bool useDependenciesInBuildField;
    
    private string subTypeField;
    
    private string minFrameworkVersionField;
    
    public VisualStudioProjectTypeAssemblyReference() {
        this.copyLocalDependenciesField = true;
        this.copyLocalSatelliteAssembliesField = true;
        this.useInBuildField = true;
        this.useDependenciesInBuildField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferenceConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationType[] ReferenceConfiguration {
        get {
            return this.referenceConfigurationField;
        }
        set {
            this.referenceConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RelativePath {
        get {
            return this.relativePathField;
        }
        set {
            this.relativePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AssemblyName {
        get {
            return this.assemblyNameField;
        }
        set {
            this.assemblyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CopyLocal {
        get {
            return this.copyLocalField;
        }
        set {
            this.copyLocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalDependencies {
        get {
            return this.copyLocalDependenciesField;
        }
        set {
            this.copyLocalDependenciesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalSatelliteAssemblies {
        get {
            return this.copyLocalSatelliteAssembliesField;
        }
        set {
            this.copyLocalSatelliteAssembliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseInBuild {
        get {
            return this.useInBuildField;
        }
        set {
            this.useInBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseDependenciesInBuild {
        get {
            return this.useDependenciesInBuildField;
        }
        set {
            this.useDependenciesInBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SubType {
        get {
            return this.subTypeField;
        }
        set {
            this.subTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinFrameworkVersion {
        get {
            return this.minFrameworkVersionField;
        }
        set {
            this.minFrameworkVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeProjectReference {
    
    private ConfigurationType[] referenceConfigurationField;
    
    private string referencedProjectIdentifierField;
    
    private string nameField;
    
    private string copyLocalField;
    
    private bool copyLocalDependenciesField;
    
    private bool copyLocalSatelliteAssembliesField;
    
    private bool useInBuildField;
    
    private bool useDependenciesInBuildField;
    
    private string relativePathToProjectField;
    
    public VisualStudioProjectTypeProjectReference() {
        this.copyLocalDependenciesField = true;
        this.copyLocalSatelliteAssembliesField = true;
        this.useInBuildField = true;
        this.useDependenciesInBuildField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferenceConfiguration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConfigurationType[] ReferenceConfiguration {
        get {
            return this.referenceConfigurationField;
        }
        set {
            this.referenceConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReferencedProjectIdentifier {
        get {
            return this.referencedProjectIdentifierField;
        }
        set {
            this.referencedProjectIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CopyLocal {
        get {
            return this.copyLocalField;
        }
        set {
            this.copyLocalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalDependencies {
        get {
            return this.copyLocalDependenciesField;
        }
        set {
            this.copyLocalDependenciesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CopyLocalSatelliteAssemblies {
        get {
            return this.copyLocalSatelliteAssembliesField;
        }
        set {
            this.copyLocalSatelliteAssembliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseInBuild {
        get {
            return this.useInBuildField;
        }
        set {
            this.useInBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool UseDependenciesInBuild {
        get {
            return this.useDependenciesInBuildField;
        }
        set {
            this.useDependenciesInBuildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RelativePathToProject {
        get {
            return this.relativePathToProjectField;
        }
        set {
            this.relativePathToProjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisualStudioProjectTypeGlobal {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum VisualStudioProjectTypeVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7.00")]
    Item700,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7,00")]
    Item7001,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7.10")]
    Item710,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7,10")]
    Item7101,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8.00")]
    Item800,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8,00")]
    Item8001,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9.00")]
    Item900,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9,00")]
    Item9001,
}
