#pragma once

namespace Earlgrey
{
	enum E_DayOfWeek
	{
		DAYOFWEEK_SUNDAY,
		DAYOFWEEK_MONDAY,
		DAYOFWEEK_TUESDAY,
		DAYOFWEEK_WEDNESDAY,
		DAYOFWEEK_THURSDAY,
		DAYOFWEEK_FRIDAY,
		DAYOFWEEK_SATURDAY
	};
}