//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.239
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuild.Earlgrey.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuild.Earlgrey.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to lookup information for {0} in Active Directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActiveDirectoryLookupException {
            get {
                return ResourceManager.GetString("ActiveDirectoryLookupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attrib directory &apos;{0}&apos;. {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AttribDirectory {
            get {
                return ResourceManager.GetString("AttribDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attrib file &apos;{0}&apos;. {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AttribFile {
            get {
                return ResourceManager.GetString("AttribFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t connect to remove server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouldNotConnectToRemoteServer {
            get {
                return ResourceManager.GetString("CouldNotConnectToRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t resolve server host name {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CouldNotResolveServerHostName {
            get {
                return ResourceManager.GetString("CouldNotResolveServerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating directory &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreatingDirectory {
            get {
                return ResourceManager.GetString("CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both &quot;{0}&quot; and &quot;{1}&quot; were specified as input parameters in the project file. Please choose one or the other.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExactlyOneTypeOfDestination {
            get {
                return ResourceManager.GetString("ExactlyOneTypeOfDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Not Found: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local File Not Found: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpLocalNotFound {
            get {
                return ResourceManager.GetString("FtpLocalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///     {0}% Complete ({1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpPercentComplete {
            get {
                return ResourceManager.GetString("FtpPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfered {0} ({1}) in {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpTransfered {
            get {
                return ResourceManager.GetString("FtpTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload File Complete, {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpUploadComplete {
            get {
                return ResourceManager.GetString("FtpUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploading &quot;{0}&quot;
        ///   to &quot;{1}&quot;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpUploading {
            get {
                return ResourceManager.GetString("FtpUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The URI &quot;{0}&quot; scheme is not valid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FtpUriInvalid {
            get {
                return ResourceManager.GetString("FtpUriInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed by {0}, from {1} to {2} byte(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JSCompressCompressed {
            get {
                return ResourceManager.GetString("JSCompressCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing JavaScript in &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JSCompressCompressing {
            get {
                return ResourceManager.GetString("JSCompressCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing compressed JavaScript back to &quot;{0}&quot; using {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JSCompressWriting {
            get {
                return ResourceManager.GetString("JSCompressWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emailing &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MailEmailing {
            get {
                return ResourceManager.GetString("MailEmailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is not a number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MathNotNumber {
            get {
                return ResourceManager.GetString("MathNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Complete: {0} files merged into &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MergeComplete {
            get {
                return ResourceManager.GetString("MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Complete: No source files to merge.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MergeCompleteNoSourceFiles {
            get {
                return ResourceManager.GetString("MergeCompleteNoSourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merging file &apos;{0}&apos; into &apos;{1}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MergingFile {
            get {
                return ResourceManager.GetString("MergingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to move file &quot;{0}&quot; to &quot;{1}&quot;. {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveError {
            get {
                return ResourceManager.GetString("MoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving file from &quot;{0}&quot; to &quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MoveFileComment {
            get {
                return ResourceManager.GetString("MoveFileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the NUnit Project File open command. Please make sure NUnit is installed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NUnitNotFound {
            get {
                return ResourceManager.GetString("NUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking Oracle Home: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OracleHomeCheck {
            get {
                return ResourceManager.GetString("OracleHomeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter &quot;{1}&quot; does not apply to the current use of task &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ParameterNotUsed {
            get {
                return ResourceManager.GetString("ParameterNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &quot;{0}&quot; task was not given a value for the required parameter &quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Windows Registry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegistryRead {
            get {
                return ResourceManager.GetString("RegistryRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write Windows Registry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegistryWrite {
            get {
                return ResourceManager.GetString("RegistryWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot continue service {0} on computer &apos;{1}&apos; as it does not support the pause and continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceCannotContinue {
            get {
                return ResourceManager.GetString("ServiceCannotContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot pause service {0} on computer &apos;{1}&apos; as it does not support the pause and continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceCannotPause {
            get {
                return ResourceManager.GetString("ServiceCannotPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot stop service {0} on computer &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceCannotStop {
            get {
                return ResourceManager.GetString("ServiceCannotStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service was continued successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceContinued {
            get {
                return ResourceManager.GetString("ServiceContinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service is continuing ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceContinuing {
            get {
                return ResourceManager.GetString("ServiceContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find the &apos;{0}&apos; service on &apos;{1}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot continue service {0} on computer &apos;{1}&apos; as its not currently paused.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceNotPaused {
            get {
                return ResourceManager.GetString("ServiceNotPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot pause service {0} on computer &apos;{1}&apos; as its not currently started.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceNotStarted {
            get {
                return ResourceManager.GetString("ServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service was paused successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServicePaused {
            get {
                return ResourceManager.GetString("ServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service is pausing ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServicePausing {
            get {
                return ResourceManager.GetString("ServicePausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service was started successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service is starting ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;{0}&apos; service on &apos;{1}&apos; is &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service was stopped successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} service is stopping ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution file &quot;{0}&quot; not found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SolutionNotFound {
            get {
                return ResourceManager.GetString("SolutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LocalPath is not a working subversion copy.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SvnLocalPathNotWorkCopy {
            get {
                return ResourceManager.GetString("SvnLocalPathNotWorkCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not {0} the file &quot;{1}&quot; to the destination file &quot;{2}&quot;, because the destination is a folder instead of a file. To {0} the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskDestinationIsDirectory {
            get {
                return ResourceManager.GetString("TaskDestinationIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No destination specified for {0}. Please supply either &quot;{1}&quot; or &quot;{2}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskNeedsDestination {
            get {
                return ResourceManager.GetString("TaskNeedsDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The source file &quot;{0}&quot; is actually a directory.  The &quot;{1}&quot; task does not support moving directories.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskSourceIsDirectory {
            get {
                return ResourceManager.GetString("TaskSourceIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get current date!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimeFormatException {
            get {
                return ResourceManager.GetString("TimeFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting current date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimeGettingCurrentDate {
            get {
                return ResourceManager.GetString("TimeGettingCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding TNSNAMES entry &quot;{0}&quot; to &quot;{1}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TnsnameAdded {
            get {
                return ResourceManager.GetString("TnsnameAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looking for {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TnsNamesFileCheck {
            get {
                return ResourceManager.GetString("TnsNamesFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to locate a TNSNAMES.ORA file. Please specify a value for TnsNamesFile.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TnsNamesFileNotFound {
            get {
                return ResourceManager.GetString("TnsNamesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TNSNAME entry &quot;{0}&quot; already exists in &quot;{1}&quot; and AllowUpdates=false.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TnsnameUpdateAborted {
            get {
                return ResourceManager.GetString("TnsnameUpdateAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating TNSNAMES entry &quot;{0}&quot; in &quot;{1}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TnsnameUpdated {
            get {
                return ResourceManager.GetString("TnsnameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{2}&quot; refers to {0} item(s), and &quot;{3}&quot; refers to {1} item(s). They must have the same number of items.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TwoVectorsMustHaveSameLength {
            get {
                return ResourceManager.GetString("TwoVectorsMustHaveSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///     extracted &quot;{0}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnzipExtracted {
            get {
                return ResourceManager.GetString("UnzipExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unzip File &quot;{0}&quot;
        ///    to Directory &quot;{1}&quot;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnzipFileToDirectory {
            get {
                return ResourceManager.GetString("UnzipFileToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unzipped file &quot;{0}&quot; successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnzipSuccessfully {
            get {
                return ResourceManager.GetString("UnzipSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commitment of change set failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultAddFileCommitFailed {
            get {
                return ResourceManager.GetString("VaultAddFileCommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files added to Vault repository successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultAddFileCommitSucceeded {
            get {
                return ResourceManager.GetString("VaultAddFileCommitSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files specified for addition to repository cannot be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultAddFilesException {
            get {
                return ResourceManager.GetString("VaultAddFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file {0} could not be checked in: {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultCheckinFileException {
            get {
                return ResourceManager.GetString("VaultCheckinFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File or folder {0} not found for checkin.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultCheckinFileNotFoundException {
            get {
                return ResourceManager.GetString("VaultCheckinFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder {0} could not be checked in: {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultCheckinFolderException {
            get {
                return ResourceManager.GetString("VaultCheckinFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} successfully checked out.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultCheckinSuccessful {
            get {
                return ResourceManager.GetString("VaultCheckinSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} successfully checked out.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultCheckoutSuccessful {
            get {
                return ResourceManager.GetString("VaultCheckoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified diskfile {0} does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultDiskFileDoesNotExist {
            get {
                return ResourceManager.GetString("VaultDiskFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File [{0}] added to change set.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultFileAddedToChangeSet {
            get {
                return ResourceManager.GetString("VaultFileAddedToChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder [{0}] added to change set.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultFolderAddedToChangeSet {
            get {
                return ResourceManager.GetString("VaultFolderAddedToChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect parameters passed to VaultSession.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultIncorrectParameters {
            get {
                return ResourceManager.GetString("VaultIncorrectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login to Vault repository failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultLoginFailed {
            get {
                return ResourceManager.GetString("VaultLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error validating path &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultPathValidationException {
            get {
                return ResourceManager.GetString("VaultPathValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection of the repository failed: {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultRepositorySelectionFailure {
            get {
                return ResourceManager.GetString("VaultRepositorySelectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File or folder {0} not found for checkout.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultResourceNotFound {
            get {
                return ResourceManager.GetString("VaultResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set working folder for {0} to {1} from {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultSetNewWorkingFolder {
            get {
                return ResourceManager.GetString("VaultSetNewWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientInstance.TreeCache has not been initialized, Common cause is that SelectRepository has not been called sucessfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultTreeCacheFailure {
            get {
                return ResourceManager.GetString("VaultTreeCacheFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully undid check out for {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultUndoCheckoutSuccessful {
            get {
                return ResourceManager.GetString("VaultUndoCheckoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Url specifying vault location is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultUrlRequired {
            get {
                return ResourceManager.GetString("VaultUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username must be set to access repository.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultUsernameRequired {
            get {
                return ResourceManager.GetString("VaultUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clearing working folder for {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultWorkingFolderCleared {
            get {
                return ResourceManager.GetString("VaultWorkingFolderCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restoring working folder for {0} to {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VaultWorkingFolderRestored {
            get {
                return ResourceManager.GetString("VaultWorkingFolderRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version file &quot;{0}&quot; not found - creating new file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionFileNotFound {
            get {
                return ResourceManager.GetString("VersionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updated to version {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionModifiedValue {
            get {
                return ResourceManager.GetString("VersionModifiedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialized to version {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionOriginalValue {
            get {
                return ResourceManager.GetString("VersionOriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading version from file &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionRead {
            get {
                return ResourceManager.GetString("VersionRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to read version number from &quot;{0}&quot;. {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionReadException {
            get {
                return ResourceManager.GetString("VersionReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to write version number to &quot;{0}&quot;. {1}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionWriteException {
            get {
                return ResourceManager.GetString("VersionWriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrote version to file &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionWrote {
            get {
                return ResourceManager.GetString("VersionWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web directory {0} does not exist on {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WebDirectoryInvalidDirectory {
            get {
                return ResourceManager.GetString("WebDirectoryInvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting scriptmap for {0} on web directory {1} on {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WebDirectoryScriptMapUpdate {
            get {
                return ResourceManager.GetString("WebDirectoryScriptMapUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web directory {0} on {1} does not have a setting called {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WebDirectorySettingInvalidSetting {
            get {
                return ResourceManager.GetString("WebDirectorySettingInvalidSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading {0} property of web directory {1} on {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WebDirectorySettingStatusRead {
            get {
                return ResourceManager.GetString("WebDirectorySettingStatusRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting {0} property of web directory {1} on {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WebDirectorySettingStatusSet {
            get {
                return ResourceManager.GetString("WebDirectorySettingStatusSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Xml Document &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlReadDocument {
            get {
                return ResourceManager.GetString("XmlReadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///     {0} node(s) selected for read.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlReadNodes {
            get {
                return ResourceManager.GetString("XmlReadNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XmlRead Result: &quot;{0}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlReadResult {
            get {
                return ResourceManager.GetString("XmlReadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating Xml Document &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlUpdateDocument {
            get {
                return ResourceManager.GetString("XmlUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///     {0} node(s) selected for update.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlUpdateNodes {
            get {
                return ResourceManager.GetString("XmlUpdateNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XmlUpdate Wrote: &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlUpdateResult {
            get {
                return ResourceManager.GetString("XmlUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding Parameter &quot;{0}&quot;: &quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XsltAddingParameter {
            get {
                return ResourceManager.GetString("XsltAddingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding root attribute {0}=&quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XsltAddingRootAttribute {
            get {
                return ResourceManager.GetString("XsltAddingRootAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating root tag &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XsltCreatingRootTag {
            get {
                return ResourceManager.GetString("XsltCreatingRootTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No input files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XsltNoInputFiles {
            get {
                return ResourceManager.GetString("XsltNoInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No root tag inserted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XsltNoRootTag {
            get {
                return ResourceManager.GetString("XsltNoRootTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///     added &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipAdded {
            get {
                return ResourceManager.GetString("ZipAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating zip file &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipCreating {
            get {
                return ResourceManager.GetString("ZipCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip File Not Found: {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipFileNotFound {
            get {
                return ResourceManager.GetString("ZipFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created zip file &quot;{0}&quot; successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZipSuccessfully {
            get {
                return ResourceManager.GetString("ZipSuccessfully", resourceCulture);
            }
        }
    }
}
