@ECHO OFF
SETLOCAL
SET MSBUILD_BATCH_FILE=MSBuild_Win32.bat
SET SET_ENVIRONMENT_FILE=SetEnvironment_Win32.bat
IF "%PROCESSOR_ARCHITEW6432%" EQU "AMD64" SET MSBUILD_BATCH_FILE=MSBuild_x64.bat
IF "%PROCESSOR_ARCHITEW6432%" EQU "AMD64" SET SET_ENVIRONMENT_FILE=SetEnvironment_x64.bat

XCOPY /Y "..\%MSBUILD_BATCH_FILE%" .
XCOPY /Y "..\%SET_ENVIRONMENT_FILE%" .

CALL "%MSBUILD_BATCH_FILE%" msbuild-deploy.xml /p:Configuration=DEBUG